### ISSUE TITLE
Unable to See Hosts/Top Talkers in Timeseries

### ISSUE THREAD

**Issue by cawhite6** [ntop/ntopng-grafana-datasource#6] opened 2018-02-07 18:30 UTC
Hope I'm missing something simple - within grafana there is no data points from my top talkers. Everything is fine within the ntopng dashboard but not showing as available in grafana panels. Essentially just my sniffer interface is available. I had an issue were the daily protocols were not working whether natively or in grafana and worked through some setting suggestions and toggle timeseries on/off (which fixed it). I don't even know where to look since obviously the datasource is working just not getting everything....any direction is appreciated.

ntopng Professional Edition v.3.2.180126

**Comment by animosity022** [comment] 2018-02-12 15:31
Can you share your config and what you are using to get that far?

**Comment by cawhite6** [comment] 2018-02-12 17:09
My config is below and maybe what I'm looking for is not even possible. After looking over ntop site and their Grafana walk through I'm not seeing a mention of what I'm trying to do - which is to create a table that shows/sorts my actual top talkers (hosts). Much like the running table to the left of the ntop native dashboards. The holy hosts I have listed are destination hosts and network (LAN) gateways.
![screen shot 2018-02-12 at 11 52 58 am](https://user-images.githubusercontent.com/15822207/36109493-96b7ae9e-0fed-11e8-8bb1-55f09d1828c5.png)
![screen shot 2018-02-12 at 12 08 41 pm](https://user-images.githubusercontent.com/15822207/36109494-96c6aa16-0fed-11e8-9c4c-b0f273a67b44.png)
![screen shot 2018-02-12 at 12 08 56 pm](https://user-images.githubusercontent.com/15822207/36109495-96d6d288-0fed-11e8-899d-6b8dcb8b866f.png)

**Comment by animosity022** [comment] 2018-02-12 18:09
How is your actual data source configured?

**Comment by cawhite6** [comment] 2018-02-12 18:12
Apologies animosity - please see below.
![screen shot 2018-02-12 at 1 12 00 pm](https://user-images.githubusercontent.com/15822207/36112055-563e4b12-0ff6-11e8-9c2d-e990697b56be.png)

**Comment by LeegacySystem** [comment] 2018-02-15 13:15
Just to add I'm seeing the same issue when trying to view host specific traffic "host_x.x.x.x_interface_tcp://y.y.y.y:zzzz_traffic_bps" in Grafana. 

Everything else seems to be running as normal, I can even view interface_* traffic without any issues.

**Comment by telekomancer** [comment] 2018-11-06 20:41
any update ? 

I have the same issue as describe, config, the same, datasource, working, but...

> Just to add I'm seeing the same issue when trying to view host specific traffic "host_x.x.x.x_interface_tcp://y.y.y.y:zzzz_traffic_bps" in Grafana.

Everything else seems to be running as normal, I can even view interface_* traffic without any issues.

**Comment by N4zroth** [comment] 2019-02-10 21:57
Bump, same for me. Most of my hosts don't have any data points and the top talkers I can see in ntopng aren't even listed under hosts in Grafana. Any idea what's going wrong?

**Comment by LeegacySystem** [comment] 2019-02-11 22:36
I never found a solution although I didn't look in depth. To me it seemed to be by design that ntopng would only stream live flow information to Grafana which simply displays what it is given rather than store it. So not all hosts would be available at all times depending on when you try to add the metric on Grafana.

I'm not sure if Grafana can plug straight into the ntopng database for historical data or if ntop can export to influxdb/prometheus/graphite which then feeds Grafana.

**Comment by simonemainardi** [comment] 2019-05-13 07:50
Closing as plugin support has been discontinued in favour of https://grafana.com/docs/features/datasources/influxdb/. See the README  https://github.com/ntop/ntopng-grafana-datasource.

**Closed as completed by simonemainardi** 2019-05-13 07:50 UTC
